// scripts/i18n/es.json is the Spanish source of truth. This writes src/i18n/es.ts from it (and first merges any
// scripts/i18n/batches/es_*.json dropped in there, which is how new translations can be added in bulk).
//
//   node scripts/i18n/build-es.mjs
import fs from 'node:fs'
import path from 'node:path'
import { ROOT } from './lib.mjs'

const dir = path.join(ROOT, 'scripts', 'i18n')
const batches = path.join(dir, 'batches')
const merged = {}

const existing = path.join(dir, 'es.json')
if (fs.existsSync(existing)) Object.assign(merged, JSON.parse(fs.readFileSync(existing, 'utf8')))

for (const name of (fs.existsSync(batches) ? fs.readdirSync(batches) : []).filter((file) => /^es_.*\.json$/.test(file)).sort()) {
  Object.assign(merged, JSON.parse(fs.readFileSync(path.join(batches, name), 'utf8')))
}

const sorted = Object.fromEntries(Object.entries(merged).sort(([a], [b]) => a.localeCompare(b)))
fs.writeFileSync(existing, JSON.stringify(sorted, null, 1) + '\n')

const quote = (value) => `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\n', '\\n')}'`
const lines = Object.entries(sorted).map(([key, value]) => `  ${quote(key)}: ${quote(value)},`)
fs.writeFileSync(
  path.join(ROOT, 'src', 'i18n', 'es.ts'),
  `/** Spanish (Spain). Generated by scripts/i18n/build-es.mjs from scripts/i18n/es.json; edit that file, not this one. */\nexport const es: Record<string, string> = {\n${lines.join('\n')}\n}\n`,
)
console.log(`${Object.keys(sorted).length} Spanish strings written`)
